name: CI

on:
  pull_request:
  push:

jobs:
  tests:
    name: 'Tests'
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2

      - name: Install Nix
        uses: cachix/install-nix-action@v13
        with:
          install_url: https://nixos-nix-install-tests.cachix.org/serve/lb41az54kzk6j12p81br4bczary7m145/install
          install_options: '--tarball-url-prefix https://nixos-nix-install-tests.cachix.org/serve'
          extra_nix_config: |
            experimental-features = nix-command flakes

      - name: Run integration tests
        run: ./run-tests.sh
