name: CI

on:
  pull_request:
  push:

jobs:
  tests:
    name: 'Tests'
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2

      - name: Install Nix
        uses: cachix/install-nix-action@v17

      - name: Run integration tests
        run: ./run-tests.sh
